## Promise API
### Promise.all
- 接受一个promise数组,并返回一个新的promise
- 当所有的promise都成功resolve,新的promise才resolve
- 如果任意一个promise被reject,由 Promise.all 返回的 promise 就会立即 reject，并且带有的就是这个 error。

```javascript
  Promise.myAll = (promises)=>{
    let count = 0 
    let arr = []
    let length = promises.length
    return new Promise((resolve,reject)=>{
      promises.forEach((item,index) => {
        Promise.resolve(item).then(res=>{
          arr[index]=res
          count++
          if(count===length){
            resolve(arr)
          }
        }).catch(err=>{
          reject(err)
        })
      });
    })
  }
```
### Promise.race
- 等待第一个settled的promise并resolve其结果或者reject其error
```javascript
  Promise.myRace = (promises) => {
    return new Promise((resolve, reject) => {
      promises.forEach((item) => {
        Promise.resolve(item).then(resolve).catch(reject);
      });
    });
  }
```
### Promise.any
- 等待第一个fulfilled的promise,并将其返回
- 如果promise都rejected,那么reject个error对象
```javascript
  Promise.myAny = (promises) => {
    let count = 0;
    let length = promises.length;
    return new Promise((resolve, reject) => {
      promises.forEach((item) => {
        Promise.resolve(item)
          .then(resolve)
          .catch(() => {
            count++;
            if (count === length) {
              reject({ error: '没有promise成功' });
            }
          });
      });
gg    });
  }
```
### Promise.allSettled
Promise.allSettled 等待所有的 promise 都被 settle，无论结果如何。结果数组具有
- {status:"fulfilled", value:result} 对于成功的响应，
- {status:"rejected", reason:error} 对于 error。
```javascript
  Promise.myAllSettled = function (promises) {
    let arr = [];
    let count = 0;
    let length = promises.length;
    return new Promise((resolve, reject) => {
      promises.forEach((item, i) => {
        Promise.resolve(item)
          .then((res) => {
            arr[i] = { status: 'fulfilled', value: res };
            count++;
            if (count === length) {
              resolve(arr);
            }
          })
          .catch((error) => {
            arr[i] = { status: 'rejected', reason: error };
            count++;
            if (count === length) {
              resolve(arr);
            }
          });
      });
    });
  }
```
## call,apply,bind
### call
call(obj,...args)
- 改变this指向,指向函数第一个参数
- 函数执行
```javascript
  Function.prototype.myCall = function (context, ...args) {
    if (typeof this !== 'function') {
      return new Error('调用对象必须是函数');
    }
    let ctx = context || windows;
    let fn = Symbol();
    ctx[fn] = this;
    args = args ? args : [];
    const res = args.length > 0 ? ctx[fn](...args) : ctx[fn]();
    delete ctx[fn];
    return res;
  }
```
### apply
apply(obj,args=[])
- 和call唯一的区别是,参数是类数组对象
```javascript
  Function.prototype.myCall = function (context, args=[]) {
    if (typeof this !== 'function') {
      return new Error('调用对象必须是函数');
    }
    let ctx = context || windows;
    let fn = Symbol();
    ctx[fn] = this;
    const res = args.length > 0 ? ctx[fn](...args) : ctx[fn]();
    delete ctx[fn];
    return res;
  }
```
### bind
- 改变this指向
- 返回一个函数
```javascript
  Function.prototype.myBind = function (context) {
    if (typeof this !== 'function') {
      throw new Error('调用对象必须是函数');
    }
    let self = this;
    const args = [...arguments].slice(1);
    return function bingFn() {
      return self.apply(this instanceof bingFn ? this : context, args.concat(...arguments));
    };
  }
```


